-- =============================================
-- HAL CINEMA 座席予約システム DB スキーマ
-- PostgreSQL 16
-- =============================================

-- ジャンル
CREATE TABLE IF NOT EXISTS genres (
    genre_id    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL UNIQUE
);

-- キャスト
CREATE TABLE IF NOT EXISTS cast_members (
    cast_id     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL
);

-- スクリーン
CREATE TABLE IF NOT EXISTS screens (
    screen_id   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL,
    screen_type VARCHAR(10) NOT NULL  -- large/medium/small
);

-- 映画
CREATE TABLE IF NOT EXISTS movies (
    movie_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(255) NOT NULL,
    title_en     VARCHAR(255),
    synopsis     TEXT,
    duration     INTEGER,          -- 分
    rating       VARCHAR(10),      -- G/PG12/R15+/R18+
    director     VARCHAR(100),
    release_date DATE,
    end_date     DATE,
    poster_path  VARCHAR(255),
    poster_color VARCHAR(20),      -- グラデーション背景色（例: #1a3a5c）
    ranking      INTEGER           -- 表示順（任意）
);

-- 映画×ジャンル（多対多）
CREATE TABLE IF NOT EXISTS movie_genres (
    movie_genre_id  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    movie_id        BIGINT NOT NULL REFERENCES movies(movie_id) ON DELETE CASCADE,
    genre_id        BIGINT NOT NULL REFERENCES genres(genre_id) ON DELETE CASCADE,
    UNIQUE (movie_id, genre_id)
);

-- 映画×キャスト（多対多）
CREATE TABLE IF NOT EXISTS movie_casts (
    movie_cast_id   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    movie_id        BIGINT NOT NULL REFERENCES movies(movie_id) ON DELETE CASCADE,
    cast_id         BIGINT NOT NULL REFERENCES cast_members(cast_id) ON DELETE CASCADE,
    UNIQUE (movie_id, cast_id)
);

-- 座席
CREATE TABLE IF NOT EXISTS seats (
    seat_id     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    screen_id   BIGINT NOT NULL REFERENCES screens(screen_id),
    seat_row    VARCHAR(2) NOT NULL,   -- A〜I
    seat_col    INTEGER NOT NULL,
    UNIQUE (screen_id, seat_row, seat_col)
);

-- 券種
CREATE TABLE IF NOT EXISTS ticket_types (
    ticket_type_id  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name            VARCHAR(50) NOT NULL,
    unit_price      INTEGER NOT NULL    -- 円
);

-- クーポン
CREATE TABLE IF NOT EXISTS coupons (
    coupon_id       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    code            VARCHAR(30) NOT NULL UNIQUE,
    discount_type   VARCHAR(10) NOT NULL,  -- amount（円引き）/ rate（割引率）
    discount_value  INTEGER NOT NULL,
    max_uses        INTEGER,               -- NULL = 無制限
    expires_at      DATE
);

-- キャンペーン
CREATE TABLE IF NOT EXISTS campaigns (
    campaign_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(255) NOT NULL,
    subtitle        VARCHAR(255),
    description     TEXT,                  -- 一覧表示用短文
    body            TEXT,                  -- 詳細本文
    period          VARCHAR(100),          -- 表示用文字列 例: "2025/7/1〜2025/8/31"
    category        VARCHAR(20) NOT NULL,  -- キャンペーン/割引情報/会員情報/お知らせ
    image_path      VARCHAR(255),
    accent_color    VARCHAR(20)            -- バッジ・グラデーション色 例: #c0392b
);

-- 会員
CREATE TABLE IF NOT EXISTS members (
    member_id       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255) NOT NULL UNIQUE,
    password_hash   VARCHAR(255),          -- OAuth会員はNULL
    last_name       VARCHAR(50) NOT NULL,
    first_name      VARCHAR(50) NOT NULL,
    last_name_kana  VARCHAR(50),
    first_name_kana VARCHAR(50),
    gender          VARCHAR(10),           -- male/female/other
    phone           VARCHAR(20),
    auth_provider   VARCHAR(20) NOT NULL DEFAULT 'local',  -- local/google
    created_at      TIMESTAMP NOT NULL DEFAULT now(),
    age             VARCHAR(3)
);

-- 好き（AIによる予測スコア格納用）
CREATE TABLE IF NOT EXISTS likes (
    like_id     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES members(member_id) ON DELETE CASCADE,
    movie_id    BIGINT NOT NULL REFERENCES movies(movie_id) ON DELETE CASCADE,
    score       INTEGER NOT NULL,
    UNIQUE (user_id, movie_id)
);

-- 上映スケジュール
CREATE TABLE IF NOT EXISTS showings (
    showing_id  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    movie_id    BIGINT NOT NULL REFERENCES movies(movie_id),
    screen_id   BIGINT NOT NULL REFERENCES screens(screen_id),
    show_date   DATE NOT NULL,
    start_time  TIME NOT NULL,
    UNIQUE (screen_id, show_date, start_time)
);

-- 予約
CREATE TABLE IF NOT EXISTS bookings (
    booking_id  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    member_id   BIGINT REFERENCES members(member_id),   -- ゲスト予約はNULL
    showing_id  BIGINT NOT NULL REFERENCES showings(showing_id),
    coupon_id   BIGINT REFERENCES coupons(coupon_id),
    booking_no  VARCHAR(20) NOT NULL UNIQUE,
    booked_at   TIMESTAMP NOT NULL DEFAULT now(),
    status      VARCHAR(20) NOT NULL DEFAULT 'pending',  -- pending/confirmed/cancelled
    expires_at  TIMESTAMP                                -- 仮予約の有効期限
);

-- 予約座席（1行=1席）
CREATE TABLE IF NOT EXISTS booking_seats (
    booking_seat_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    booking_id      BIGINT NOT NULL REFERENCES bookings(booking_id),
    showing_id      BIGINT NOT NULL REFERENCES showings(showing_id),
    seat_id         BIGINT NOT NULL REFERENCES seats(seat_id),
    ticket_type_id  BIGINT NOT NULL REFERENCES ticket_types(ticket_type_id),
    applied_price   INTEGER NOT NULL,  -- 予約時点の単価（価格変動対応）
    UNIQUE (showing_id, seat_id)       -- 二重予約防止
);

-- 支払い
CREATE TABLE IF NOT EXISTS payments (
    payment_id      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    booking_id      BIGINT NOT NULL REFERENCES bookings(booking_id) UNIQUE,
    method          VARCHAR(20) NOT NULL,              -- credit/emoney/qr
    amount          INTEGER NOT NULL,                  -- 円
    status          VARCHAR(20) NOT NULL DEFAULT 'unpaid',  -- unpaid/paid/refunded/failed
    paid_at         TIMESTAMP,
    transaction_id  VARCHAR(100)                       -- Stripe PaymentIntent ID など
);

-- チケット（QRコード）
CREATE TABLE IF NOT EXISTS tickets (
    ticket_id       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    booking_seat_id BIGINT NOT NULL REFERENCES booking_seats(booking_seat_id) UNIQUE,
    qr_token        VARCHAR(64) NOT NULL UNIQUE,       -- 入場用トークン
    status          VARCHAR(20) NOT NULL DEFAULT 'unused',  -- unused/used
    used_at         TIMESTAMP
);

-- ポイント履歴
CREATE TABLE IF NOT EXISTS point_transactions (
    point_tx_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    member_id   BIGINT NOT NULL REFERENCES members(member_id),
    booking_id  BIGINT REFERENCES bookings(booking_id),
    amount      INTEGER NOT NULL,      -- 正=獲得 / 負=利用
    tx_type     VARCHAR(20) NOT NULL,  -- earn/use/expire
    created_at  TIMESTAMP NOT NULL DEFAULT now()
);

-- 通知
CREATE TABLE IF NOT EXISTS notifications (
    notification_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    member_id       BIGINT NOT NULL REFERENCES members(member_id),
    booking_id      BIGINT REFERENCES bookings(booking_id),
    type            VARCHAR(20) NOT NULL,  -- confirm/reminder/cancel
    body            TEXT NOT NULL,
    sent_at         TIMESTAMP,
    is_read         BOOLEAN NOT NULL DEFAULT FALSE
);


-- =============================================
-- インデックス
-- =============================================

-- 上映検索（日付絞り込みが多い）
CREATE INDEX IF NOT EXISTS idx_showings_movie_date ON showings (movie_id, show_date);
CREATE INDEX IF NOT EXISTS idx_showings_screen_date ON showings (screen_id, show_date);

-- 予約検索
CREATE INDEX IF NOT EXISTS idx_bookings_member ON bookings (member_id);
CREATE INDEX IF NOT EXISTS idx_bookings_showing ON bookings (showing_id);

-- 予約座席：空席確認
CREATE INDEX IF NOT EXISTS idx_booking_seats_showing ON booking_seats (showing_id);

-- 通知未読検索
CREATE INDEX IF NOT EXISTS idx_notifications_member_unread ON notifications (member_id, is_read);

-- ポイント履歴
CREATE INDEX IF NOT EXISTS idx_point_tx_member ON point_transactions (member_id);
